### ISSUE TITLE
Trouble building image locally

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/superpixel-classification#5]
I'm up to date with `origin/main`, but running `docker build --force-rm --no-cache -t dsarchive/superpixel .` results in the following error:

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /opt/scw
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by manthey** [comment]
Hmm?  My working directory is clean (`git status --ignored` shows no files that aren't checked in).  Is it possible `docker pull tensorflow/tensorflow:latest-gpu` is cached and out of date with an older version of pip inside it?

**Comment by naglepuff** [comment]
You're right, pulling the tensorflow image solved the problem
